const states = {
  "Alabama": ["Birmingham", "Huntsville", "Mobile", "Montgomery"],
  "Alaska": ["Anchorage"],
  "Arizona": ["Chandler", "Gilbert", "Glendale", "Mesa", "Peoria", "Phoenix", "Scottsdale", "Tempe", "Tucson"],
  "Arkansas": ["Little-Rock"],
  "California": ["Anaheim", "Antioch", "Bakersfield", "Berkeley", "Burbank", "Chula-Vista", "Concord", "Corona", "Costa-Mesa", "Daly-City", "Downey", "El-Monte", "Elk-Grove", "Escondido", "Fairfield", "Fontana", "Fremont", "Fresno", "Fullerton", "Garden-Grove", "Glendale", "Hayward", "Huntington-Beach", "Inglewood", "Irvine", "Lancaster", "Long-Beach", "Los-Angeles", "Modesto", "Moreno Valley", "Norwalk", "Oakland", "Oceanside", "Ontario", "Orange", "Oxnard", "Palmdale", "Pasadena", "Pomona", "Rancho-Cucamonga", "Richmond", "Riverside", "Roseville", "Sacramento", "Salinas", "San-Bernardino", "San-Buenaventura-(Ventura)", "San-Diego", "San-Francisco", "San-Jose", "Santa-Ana", "Santa-Clara", "Santa-Clarita", "Santa-Rosa", "Simi-Valley", "Stockton", "Sunnyvale", "Thousand-Oaks", "Torrance", "Vallejo", "Victorville", "Visalia", "West-Covina"],
  "Colorado": ["Arvada", "Aurora", "Boulder", "Centennial", "Colorado-Springs", "Denver", "Fort-Collins", "Lakewood", "Thornton", "Westminster"],
  "Connecticut": ["Bridgeport", "Hartford", "New-Haven", "Stamford", "Waterbury"],
  "District-of-Columbia": ["Washington"],
  "Florida": ["Cape-Coral", "Clearwater", "Coral-Springs", "Fort-Lauderdale", "Gainesville", "Hialeah", "Hollywood", "Jacksonville", "Miami", "Miami-Gardens", "Miramar", "Orlando", "Palm-Bay", "Pembroke-Pines", "Pompano-Beach", "Port-St.Lucie", "Tallahassee", "Tampa", "St.Petersburg"],
  "Georgia": ["Athens", "Atlanta", "Augusta", "Columbus", "Savannah"],
  "Hawaii": ["Honolulu"],
  "Idaho": ["Boise"],
  "Illinois": ["Aurora", "Chicago", "Elgin", "Joliet", "Naperville", "Peoria", "Rockford", "Springfield"],
  "Indiana": ["Evansville", "Fort-Wayne", "Indianapolis", "South-Bend"],
  "Iowa": ["Cedar-Rapids", "Davenport", "Des-Moines"],
  "Kansas": ["Olathe", "Overland-Park", "Topeka", "Wichita"],
  "Kentucky": ["Lexington", "Louisville"],
  "Louisiana": ["Baton-Rouge", "Lafayette", "New-Orleans", "Shreveport"],
  "Maryland": ["Baltimore"],
  "Massachusetts": ["Boston", "Cambridge", "Lowell", "Springfield", "Worcester"],
  "Michigan": ["Ann-Arbor", "Detroit", "Flint", "Grand-Rapids", "Lansing", "Sterling-Heights", "Warren"],
  "Minnesota": ["Minneapolis", "Rochester", "St.Paul"],
  "Missouri": ["Columbia", "Independence", "Kansas-City", "Springfield", "St.Louis"],
  "Montana": ["Billings"],
  "Nebraska": ["Lincoln", "Omaha"],
  "Nevada": ["Henderson", "Las-Vegas", "North-Las-Vegas", "Reno"],
  "New-Hampshire": ["Manchester"],
  "New-Jersey": ["Elizabeth", "Jersey-City", "Newark", "Paterson"],
  "New-Mexico": ["Albuquerque"],
  "New-York": ["Buffalo", "New-York", "Rochester", "Syracuse", "Yonkers"],
  "North-Carolina": ["Cary", "Charlotte", "Durham", "Fayetteville", "Greensboro", "High-Point", "Raleigh", "Wilmington", "Winston-Salem"],
  "North-Dakota": [],
  "Ohio": ["Akron", "Cincinnati", "Cleveland", "Columbus", "Dayton", "Toledo"],
  "Oklahoma": ["Norman", "Oklahoma-City", "Tulsa"],
  "Oregon": ["Eugene", "Gresham", "Portland", "Salem"],
  "Pennsylvania": ["Allentown", "Erie", "Philadelphia", "Pittsburgh"],
  "Rhode-Island": ["Providence"],
  "South-Carolina": ["Charleston", "Columbia"],
  "South-Dakota": ["Sioux-Falls"],
  "Tennessee": ["Chattanooga", "Clarksville", "Knoxville", "Memphis", "Murfreesboro", "Nashville"],
  "Texas": ["Abilene", "Amarillo", "Arlington", "Austin", "Beaumont", "Brownsville", "Carrollton", "Corpus-Christi", "Dallas", "Denton", "El-Paso", "Fort-Worth", "Frisco", "Garland", "Grand-Prairie", "Houston", "Killeen", "Laredo", "Lewisville", "McAllen", "McKinney", "Mesquite", "Midland", "Pasadena", "Plano", "Richardson", "Round-Rock", "San-Antonio", "Waco", "Wichita-Falls"],
  "Utah": ["Provo", "Salt-Lake-City", "West-Jordan", "West-Valley-City"],
  "Virginia": ["Alexandria", "Arlington", "Chesapeake", "Hampton", "Newport News", "Norfolk", "Richmond", "Virginia-Beach"],
  "Washington": ["Bellevue", "Seattle", "Spokane", "Tacoma", "Vancouver"],
  "Wisconsin": ["Green-Bay", "Madison", "Milwaukee"]
};
